version: '3.7'
services:
  cache:
    image: redis
    hostname: cache
    container_name: cache
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      net:
    volumes:
      - ./redis-data:/data
    expose:
      - 6379
    ports:
      - '6379:6379'
  db:
    image: postgres
    hostname: db
    container_name: db
    networks:
      net:
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test-db
      PGDATA: /var/lib/postgresql/data

    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  backend:
    build: .
    container_name: backend
    ports:
     - '4000:4000'
    networks:
      net:
    depends_on:
      - cache
      - db
volumes:
   pgdata:
     driver: local

networks:
  net: